name: "Feature (Epic)"
description: "Вставьте целиком спецификацию фичи"
labels: ["feature","epic"]
body:
  - type: textarea
    id: spec
    attributes:
      label: Спецификация (одним блоком Markdown)
      description: |
        Вставьте текст из GPT. ВАЖНО: сделайте раздел **## План** со списком чекбоксов,
        это и есть очередность шагов для Codex.
      placeholder: |
        # Название
        ## Задача/ценность
        ...
        ## Acceptance Criteria
        - [ ] ...
        - [ ] ...
        ## План
        - [ ] Шаг 1
        - [ ] Шаг 2
        - [ ] Шаг 3
        ## Риски/QA/Роллаут
        ...
    validations: { required: true }
