name: Auto PR for Codex branches
on:
  push:
    branches:
      - 'feature/cx-*'   # под свой шаблон

permissions:
  contents: write
  pull-requests: write

jobs:
  open_or_update_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Open or update PR
        uses: actions/github-script@v7
        with:
          script: |
            const core = require('@actions/core');
            const branchRef = process.env.GITHUB_REF; // refs/heads/feature/cx-1234-...
            const branch = branchRef.replace('refs/heads/','');
            const owner = context.repo.owner;
            const repo  = context.repo.repo;
            const base  = 'main'; // или ваша основная ветка

            const title = `Codex: ${branch}`;
            const body  = [
              `Авто-PR от Codex для ветки \`${branch}\`.`,
              '',
              '<!-- source=codex auto-pr -->'
            ].join('\n');

            // есть ли уже открытый PR с этой head-веткой?
            const { data: prs } = await github.rest.pulls.list({
              owner, repo, state: 'open', head: `${owner}:${branch}`
            });

            if (prs.length === 0) {
              const create = await github.rest.pulls.create({
                owner, repo, head: branch, base, title, body, draft: false
              });
              core.notice(`PR создан: #${create.data.number}`);
            } else {
              const pr = prs[0];
              await github.rest.pulls.update({ owner, repo, pull_number: pr.number, title, body });
              core.notice(`PR обновлён: #${pr.number}`);
            }
